// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhhlU9Mu-skfcdl7WI8T_Wk2rI3ksRhtc',
    appId: '1:455595449805:web:5597a9608c17547fd57884',
    messagingSenderId: '455595449805',
    projectId: 'gestor-tareas-de984',
    authDomain: 'gestor-tareas-de984.firebaseapp.com',
    storageBucket: 'gestor-tareas-de984.firebasestorage.app',
    measurementId: 'G-QZPMEZ2BQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_-cM3feYCIj4nrlLqaU3aCKP0Q2bGrZQ',
    appId: '1:455595449805:android:a5ca280478fe348bd57884',
    messagingSenderId: '455595449805',
    projectId: 'gestor-tareas-de984',
    storageBucket: 'gestor-tareas-de984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_rlAfvm95WMBEd-QNYuuIWCxwC30I85Y',
    appId: '1:455595449805:ios:743e6df7d84ec67ed57884',
    messagingSenderId: '455595449805',
    projectId: 'gestor-tareas-de984',
    storageBucket: 'gestor-tareas-de984.firebasestorage.app',
    iosBundleId: 'com.example.gestorTareas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_rlAfvm95WMBEd-QNYuuIWCxwC30I85Y',
    appId: '1:455595449805:ios:743e6df7d84ec67ed57884',
    messagingSenderId: '455595449805',
    projectId: 'gestor-tareas-de984',
    storageBucket: 'gestor-tareas-de984.firebasestorage.app',
    iosBundleId: 'com.example.gestorTareas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhhlU9Mu-skfcdl7WI8T_Wk2rI3ksRhtc',
    appId: '1:455595449805:web:d19a6a44efec6659d57884',
    messagingSenderId: '455595449805',
    projectId: 'gestor-tareas-de984',
    authDomain: 'gestor-tareas-de984.firebaseapp.com',
    storageBucket: 'gestor-tareas-de984.firebasestorage.app',
    measurementId: 'G-HCLBD2N0BH',
  );
}
